backend:
  name: github
  # 请将下面的信息替换为你的实际 GitHub 用户名和仓库名（例如：VigorSzvigor/slat-main）
  repo: minge4237-creator/slat
  branch: main
  # 请将下面的地址替换为你部署在 Cloudflare Worker 上的 OAuth 验证服务地址
  base_url: https://slat-1oy.pages.dev/.workers.dev

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Slat Panels"
    folder: "src/content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Material", name: "material", widget: "string"}
      - {label: "Color", name: "color", widget: "string"}
      # 这是展现在主页的首图，也是详情页5张图里的第1张
      - {label: "Feature Image", name: "image", widget: "image"}
      # 这是详情页剩下的4张图
      - {label: "Gallery Images", name: "gallery", widget: "list", field: {label: "Image", name: "image", widget: "image"}, required: false}
      # 页面下半部分的详细说明
      - {label: "Body", name: "body", widget: "markdown"}
